name: Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
         reviewdog_version: latest
      - name: Run ktlint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
        run: ./gradlew ktlint --continue --quiet | reviewdog -f=checkstyle -reporter=github-pr-review
